version: '3'

services:
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '${JWT_KEY}'
      MERCURE_SUBSCRIBER_JWT_KEY: '${JWT_KEY}'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins *
        anonymous
        use_forwarded_headers "1"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${INSTANCE}.entrypoints=http"
      - "traefik.http.routers.${INSTANCE}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.middlewares.${INSTANCE}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${INSTANCE}.middlewares=${INSTANCE}-https-redirect"
      - "traefik.http.routers.${INSTANCE}-secure.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${INSTANCE}-secure.entrypoints=https"
      - "traefik.http.routers.${INSTANCE}-secure.tls=true"
      - "traefik.http.routers.${INSTANCE}-secure.tls.certresolver=http"
    volumes:
      - mercure_data:/data
      - mercure_config:/config
    networks:
      - traefik-proxy

volumes:
  mercure_data:
  mercure_config:

networks:
  traefik-proxy:
    external: true
